# pls refer https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
name: 🐞 Bug Report 
description: File a bug report
title: "[Bug]: "
labels: [Type/Bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: Connector-name
    attributes:
      label: Connector Name
      description: Choose the connector you are reporting the bug against
      options:
        - connectors/openapi (Open API Connector)
        - module/aws-s3 (AWS S3)
        - module/aws-sqs (AWS SQS)
        - module/azure-ad (Azure Active Directory)
        - module/azure-eventhub (Azure Event Hub)
        - module/azure-servicebus (Azure Servicebus)
        - module/azure-storageservice (Azure Blob & Storage Service)
        - module/cosmosdb (Cosmos DB)
        - module/gcalendar (Google Calendar)
        - module/gdrive (Google Drive)
        - module/github (Github)
        - module/gmail (Gmail)
        - module/google-peopleapi (People API)
        - module/gsheet (Google Sheet)
        - module/microsoft-excel (MS Excel)
        - module/microsoft-onedrive (MS OneDrive)
        - module/microsoft-onenote (MS OneNote)
        - module/microsoft-teams (MS Teams)
        - module/mongodb (Mongo DB)
        - module/netsuite (Netsuite)
        - module/outlook-calendar (Outlook Calendar)
        - module/outlook-mail (Outlook Mail)
        - module/redis (Redis)
        - module/salesforce (Salesforce)
        - module/slack (Slack)
        - module/snowflake (SnowFlake)
        - module/twilio (Twilio)
        - module/twitter (Twitter)
        - other (None Listed Above)
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
