# pls refer https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
name: Bug Report New
description: File a bug report
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Connector-name
    attributes:
      label: Connector Name
      description: Choose the connector you are reporting the bug against
      options:
        - connectors/openapi (Open API Connector)
        - module/aws-s3 (AWS S3)
        - module/aws-sqs (AWS SQS)
        - module/azure-ad (Azure AD)
        - module/azure-eventhub (Azure Eventhub)
        - module/azure-servicebus (Azure Service Bus)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
