on:
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            var body = github.event.comment.body
            console.log('AAAAAAAAAAAA')
            console.log(body)

