name: Add Label
on:
  issues:
    types: opened
jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/github-script@v3
          with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
          var body = github.event.comment.body
          if(true) {
              github.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['module/aws-s3']
              })
          }